config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :menus
  end
  resources :venues do
    resources :menus
  end
  resources :places do
    resources :menus
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :diagrams
      resources :canvases
      resources :shapes
    end
  end

  resources :messages
  resources :data_files

  resources :uploads do
    # collection do
    #   post 'upload'
    # end
  end
  # match "/websocket", :to => ActionCable.server, via: [:get, :post]
  mount ActionCable.server => "/websocket"

  root 'messages#index'

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
# encoding: utf-8
# frozen_string_literal: true
class Menu < ApplicationRecord
  mount_uploader :datafile, MenuUploader

  has_and_belongs_to_many :venues
  has_many   :menu_pages
  belongs_to :event
  belongs_to :place

  self.per_page = 10

  ransacker :json_export do |r|
    r.table[:json_export]
  end

  COLS = %i(
    id
    name
    sponsor
    event_orig
    venue_orig
    place_orig
    physical_description
    occasion
    notes
    call_number
    keywords
    language
    sheduled_on
    location
    location_type
    currency
    currency_symbol
    status
    menu_pages_count
    dishes_count
    place_id
    event_id
  ).freeze
end

app/controllers/menus_controller.rb
# encoding: utf-8
# frozen_string_literal: true
class MenusController < ApplicationController
  def index
    @search = ransack_params
    @menus = ransack_result

    # REVIEW: export to json if user opts to with checkbox
    render formats: :json if (params[:q][:json_export].to_i == 1 rescue false)
  end

  private

  def ransack_params
    q = params[:q]

    # REVIEW: limit results with nested resources
    if (venue_id = params[:venue_id])
      Menu.joins(:menus_venues)
          .where(menus_venues: {venue_id: venue_id})
          .ransack(q)

    elsif (event_id = params[:event_id])
      Menu.where(event_id: event_id)
          .ransack(q)

    elsif (place_id = params[:place_id])
      Menu.where(place_id: place_id)
          .ransack(q)

    else
      Menu.ransack(q)
    end
  end

  def ransack_result
    @search.result.page(params[:page])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @menu = Menu.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def menu_params
    params.fetch(:menu, {})
  end
end

app/helpers/menus_helper.rb
# encoding: utf-8
# frozen_string_literal: true
module MenusHelper
  def action
    if action_name == 'advanced_search'
      :post
    else
      :get
    end
  end

  def display_menu_results_header(count)
    if count > results_limit
      "Showing #{results_limit} results (page #{params.fetch(:page, 1)}) " \
        "out of #{count} total" \
    else
      "Your #{pluralize(count, 'result')}"
    end
  end

  def display_menu_sort_column_headers(search)
    res = \
      menu_column_headers.reduce(String.new) do |string, field|
        string << content_tag('th', sort_link(search, field, {}, method: action))
      end

    res.html_safe
  end

  def display_menu_search_results(objects)
    objects.limit(results_limit).reduce(String.new) do |string, object|
      string << content_tag('tr', display_menu_search_results_row(object))
    end.html_safe
  end

  def display_menu_search_results_row(object)
    res = \
      menu_column_fields.reduce(String.new) do |string, field|
        string << content_tag('td', object.send(field))
      end

    res .html_safe
  end

  def results_limit
    # max number of search results to display
    10
  end

  def menu_column_headers
    %i(id notes sheduled_on created_at updated_at).freeze
  end

  def menu_column_fields
    %i(id notes sheduled_on created_at updated_at).freeze
  end

  def display_query_sql(object)
    tag.p('SQL:') + tag.code(object.to_sql)
  end
end

app/views/menus/_results.html.haml
= # display_query_sql(@places)
%h2= display_menu_results_header(@search.result.size)
%table.table.table-striped
  %thead= display_menu_sort_column_headers(@search)
  %tbody= display_menu_search_results(@menus)

app/views/menus/index.html.haml
%p#notice= notice

%h1 Menus

-# REVIEW search, sort and export to json in one place with ransack help
- if params[:place_id]
  = search_form_for @search, url: place_menus_path do |f|

    %fieldset
      %legend 'Search Menus'
      %ul
        %li
          = f.label 'Notes'
          = f.text_field :notes_cont
        %li
          = f.label 'Sheduled on from'
          = f.text_field :sheduled_on_gteq
        %li
          = f.label 'Sheduled on to'
          = f.text_field :sheduled_on_lteq
        %li
          = f.label 'Export to json'
          = f.check_box :json_export
      = submit_tag 'Apply'

= will_paginate @menus
= render 'results'
= will_paginate @menus

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>